### ISSUE TITLE
Create Steam release

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/Play#382]
### Motivation
My primary goal at the moment is to release UltraStar Play on Steam for a fair price.
This could finance further development. And with enough income, commercially licensed song packages could become feasible.

### Private Repository
Sadly, the [Kickstarter campaign](https://www.kickstarter.com/projects/anst/ultrastar-play) did not end successfully.
As a result, development of the relevant features will continue in a private repository for a while until the Steam sales have compensated development costs.

### Tasks
- [x] integrate [C# bindings](https://steamworks.github.io/) of the Steam API ([Steamworks](https://partner.steamgames.com/))
- [x] add [Steam achievements](https://partner.steamgames.com/doc/features/achievements/ach_guide)
- <del> integrate [Steam workshop](https://steamcommunity.com/workshop/), e.g., for user defined themes</del>
- [x] custom build that includes Spleeter (audio separation) and Vosk (speech recognition) so users do not need to configure these manually

**Comment by achimmihca** [comment]
> achievements

Do you have any ideas / wishes for achievements?

> Steam workshop

Do you have any ideas / wishes for stuff that should be included in workshops?

Note that sharing songs through the Steam workshop will probably not be possible due to copyright issues.

**Comment by BanCrash** [comment]
> Do you have any ideas / wishes for stuff that should be included in workshops?

New party modes created by users. Not sure what would require this, but would be awesome that anyone could create their own party mode and share on the workshop.

**Comment by basisbit** [comment]
maybe allow for sharing of content that explicitly is licensed under creative commons or public domain?

**Comment by DerDorius** [comment]
> Do you have any ideas / wishes for achievements?

1. interrupt a song (Pause), Name:  Clearing the throat / Throat break
2. Stop in the middle of a Song to Songselection,  Name:  
3. Reach specific Score, Name: something like Superstar, Natural talent, Angelic voice
4.  Watch Credits, Name: Curios
5. Open Song Editor, Name: (?)
6. Save first Song, Name: Creator
7. Play own Song, Name: (?)
8. Play a Song alone, Name: Alone Wolf
9. Play a Song with 2 Players,  Name: (?)
10. Play a Song with 6 Players, Name (?)
11. Connect a Companion App, Name:  IT expert
12. Have more than 100 Songs in Song Directory, Name: Hoarder
13.  Use Webcam, Name: Narcissistic
14. Play Partymode, Name: Party Animal

These are some Suggestions/Ideas. 
I'm not a native English Speaker so its hard for me to come up with creative Names for the Achievments, maby somebody else could help here out.

**Comment by achimmihca** [comment]
- build and test on macOS
- build and test on Linux

I have to prioritize issues because time is running short. I found some new issues on macOS (which was expected) and Linux probably also will require some extra polishing.

Thus, I plan to release Windows version first as this is my primary development environment.
Afterwards, I can focus on the other platforms.

**Comment by achimmihca** [comment]
> maybe allow for sharing of content that explicitly is licensed under creative commons or public domain?

No need to explicitly allow this. This is covered by the license itself and I don't want to repeat the license. Otherwise, people might wonder why I don't also explicitly name license XYZ

**Comment by achimmihca** [comment]
> New party modes created by users. Not sure what would require this, but would be awesome that anyone could create their own party mode and share on the workshop.

Thanks for the suggestion!
I discuss ways how this could be implemented in #394

**Comment by achimmihca** [comment]
> integrate [Steam workshop](https://steamcommunity.com/workshop/), e.g., for user defined themes

This will not be included for the initial Steam release.
I plan to add Steam Workshop features later.
